### ISSUE TITLE
Please support client certificate authentication on FF

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#1068]
Correct me if I am wrong, but it seems that Browser does not support authentification with client certificates when the browser (like FF) uses its own cert store. 
In my case it is required to start a test with FF.
It would be great to have a way to import certificates (in general) in an automated way before FF starts. 
Thanks!

**Comment by aaltat** [comment]
Do you have some links to Playwright docs or something how that can be done?

**Comment by simonmeggle** [comment]
Yes (sorry): 
In [this Playwright issue](https://github.com/microsoft/playwright/issues/1799) it is shown how it can be done with JS. 
As far as I can understand.

**Comment by aaltat** [comment]
Well there is not official API available. Also there seems to be many workarounds available, based on the OS one uses. Because there is not good way to do this, in Browser library, I am going to close this issue. If Playwright API is enhanced and support is provided by Playwright, we can consider doing this one.
