### ISSUE TITLE
Set browsers windows size

### ISSUE THREAD

**Issue by eldaduzman** [MarketSquare/robotframework-browser#113]
**Is your feature request related to a problem? Please describe.**
Some web applications require larger screen size (or even full screen) to work

**Describe the solution you'd like**
a key word that allows changing the windows size of the browses.

**Comment by Snooz82** [comment]
`Set Viewport Size` => `page.setViewportSize(viewportSize)`
https://github.com/microsoft/playwright/blob/master/docs/api.md#pagesetviewportsizeviewportsize

This should be one option. 
And the other Option should be to set the Viewport Size while Creating a `New Page`

**Comment by eldaduzman** [comment]
I tried to use the 'execute java script on page' with that script but I don't have a pointer to the page element,
in any case adding a dedicated keyword would be awesome.

Thanks :)

**Comment by eldaduzman** [comment]
Implemented here => [120](https://github.com/MarketSquare/robotframework-browser/issues/120)

**Comment by Snooz82** [comment]
@eldaduzman 
I still only changes the inner viewport of the page, which means the browser itself might be bigger or smaller. It is not directly related to the browser size.

Also browser position could be implemented in the future for chromium. At the moment this feature is missing in Playwright itself.

**Comment by eldaduzman** [comment]
@Snooz82 ammm I understand,
I'll reopen.

**Comment by xylix** [comment]
As far as I know currently we don't have a way to directly set Browser size either in Playwright. So we're kind of depending on upstream to be able to improve on this.

**Comment by xylix** [comment]
@Snooz82 Now that we also expose setting context's viewport size I'm unsure if theres any need to keep this open. Can you elaborate what you meant by
```
 I still only changes the inner viewport of the page, which means the browser itself might be bigger or smaller. It is not directly related to the browser size.
```
In the context of the page I don't believe there is any other size than the viewport which the page can access. With playwright you can set a bigger viewport than the current "browser size" so that shouldn't be a problem either.

If there's a need for some feature here, I think we should aim to create an upstream ticket for it. If there's no needed feature I think we can close this.
