### ISSUE TITLE
Pip does not clean inside site-packages/Browser/wrapper anymore when uninstalling

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#1253]
When running `pip uninstall` it says `Would not remove (might be manually added):` and lists all the files inside `site-packages/Browser/wrapper`.

This means that our workaround of using the site-packages/Browser/wrapper to let pip clean it up for users is useless right now. And many gigabytes of unnecessary files will be left hanging.

Possible solutions:
- Fix the uninstall (add some new hook, figure out why pip stopped this behaviour, can the old be enabled?)
- Yield to the playwright solution of using a single system-wide directory for the browsers
- Offer new `rfbrowser uninstall` command

**Comment by aaltat** [comment]
Pip keeps track on files that it installs and cleans only files that it did install. We could add files to the RECORD file which pip creates and most likely that way also the files created `rfbroser init` will get deleted when pip uninstall command is run. But that file is pip internal thing and if/when it changes, we could need to keep up with the format. Also we would need test with different platforms, because file content may be different in different platforms. Also could not find any clear API which could be used to hook in to pip install process. I guess using pip to uninstall automatically all is not the best way to go. 

Another option would be to in Playwright Python direction. Then we would need build and store all binaries in some external blob storage (which will store the binary blobs for very long time). Also we would need to build binary blob for all major OS system. It would require quite a lot of extra work to change our packaging to something more better, although I agree that getting rid of `rfbrowser init` is a goal which might be worth of reaching. 

But I think the most simplest choice is to enhance `rfbrowser` with `uninstall` or similar argument and instruct people to use it before running `pip uninstall robotframework-browser`

**Comment by aaltat** [comment]
Did go with `rfbrowser clean-node` command
