### ISSUE TITLE
[Question] Support for native mobile browser

### ISSUE THREAD

**Issue by tremkonzah** [MarketSquare/robotframework-browser#1317]
I see in the documentation browser library have capablity to emulate mobile browser

Is there any plan to support native mobile browser and to run browser library testing on real mobile devices?

**Comment by aaltat** [comment]
That depends more on the underlying Playwright and where it develops it features. But last time I did look, which was long time ago, Playwright didn't have such plans.

**Comment by tremkonzah** [comment]
@aaltat Seems they have experimental support on native android browser, would be possible to add as experimental feature for browser library?

https://github.com/microsoft/playwright/blob/master/docs/src/api/class-android.md

https://github.com/microsoft/playwright/issues/6906
https://github.com/microsoft/playwright/issues/1122

**Comment by aaltat** [comment]
Did not know that, interesting that Playwright is also going forward to that front. There is similar type of enhancement request, in #867 , but for Electron app. But the answer is same, mobile browser support is difficult because it doesn't use the browser/context/page model. Instead it's single page, therefore it is difficult to incorporate to our library. I am not saying that it could not be done, perhaps not in near future.

**Comment by mkorpela** [comment]
Native app testing at least is out of scope. Those do not run in a browser.

**Comment by aaltat** [comment]
I agree mobile is out of our domain. Closing.
