### ISSUE TITLE
Text get deleted from input field 

### ISSUE THREAD

**Issue by tremkonzah** [MarketSquare/robotframework-browser#1324]
**Describe the bug**
Text being deleted from input field when I have two or more input field

e.g in below scenario
Scenario 1: FIELD1 get deleted when input text to FIELD2
Scenario 2: FIELD 2 get deleted when input text to FIELD1

**To Reproduce**
Sequence (scenario 1)
Browser.Type Text or Browser.Fill Text           ${FIELD1}       userid
Browser.Type Text or Browser.Fill Text           ${FIELD2}       password

Sequence (scenario 2)
Browser.Type Text or Browser.Fill Text           ${FIELD2}       password
Browser.Type Text or Browser.Fill Text           ${FIELD1}       userid

**Expected behavior**
Field1 or Field2 text should not get deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Library Version: 8.0.2

**Comment by aaltat** [comment]
In certain conditions I can get similar results. If my selector is not unique and strict mode is disabled, then keyword can overwrite text from wrong element. Example if my test looks like this:
```
Type Text In Two Fields
    Set Strict Mode    False
    Type Text    input    username
    Type Text    input    password
    Get Text    input#username_field    ==    username
    Get Text    input#password_field    ==    password
```
Then my test will fail because `input` is too generic and selector will always point to first element in page. In this case second `Type Text` will overwrite the text in the first element. In practice result will look like this:

![0-fail-screenshot-1](https://user-images.githubusercontent.com/2665023/133854679-bd47b437-ae90-4a79-82f3-3d1459d76dfc.png)

If I change my test, so that selectors are unique, keyword writes to correct field, example like this:
```
    Type Text    input#username_field    username
    Type Text    input#password_field    password
    Get Text    input#username_field    ==    username
    Get Text    input#password_field    ==    password
```
Then test works successfully. Have you tired to run the test with strict mode enabled?

**Comment by tremkonzah** [comment]
Thanks @aaltat I have enable strict mode and update my selectors
