### ISSUE TITLE
Browser Library should treat &nbsp; like white-space

### ISSUE THREAD

**Issue by robinmatz** [MarketSquare/robotframework-browser#1325]
Hi there!

First of all, I love your project! I'm migrating my SeleniumLibrary test cases to Browser and I enjoy its way of locating elements and asserting.

During the migration I have encountered a challenge that I have not yet seen an answer to. Namely, the handling of ``&nbsp;`` elements in html code. 

Given the following html snippet

```
<!DOCTYPE html>
<html>

  <head>
      <meta lang="en" charset="utf-8">
  </head>
  
  <body>
      <div id="main">Hello&nbsp;Space</div>
  </body>

</html>
```

I wanted to write a test case like this

```
*** Settings ***
Library    Browser

*** Test Cases ***
Validate No Break Space
    [Documentation]    Should verify that div's content is "Hello Space"
    New Browser    headless=False
    New Page    ${CURDIR}${/}index.html
    Get Text    id=main    ==    Hello Space
```

However, this results in test case failure
![grafik](https://user-images.githubusercontent.com/76647407/133821668-e6ae018b-aedb-4441-bfc4-3d487bad8ed6.png)

I would like Browser Library to **handle ``%nbsp;`` element as if it was a regular white-space character**.

These are the dependencies for the above example:

```
backports.cached-property==1.0.1
grpcio==1.40.0
grpcio-tools==1.40.0
overrides==6.1.0
protobuf==3.17.3
robotframework==4.1.1
robotframework-assertion-engine==0.2.0
robotframework-browser==8.0.2
robotframework-pythonlibcore==3.0.0
six==1.16.0
typing-extensions==3.10.0.2
typing-utils==0.1.0
wrapt==1.12.1
```

Feel free to reach out in case there are any questions.

Regards,
Robin

**Comment by aaltat** [comment]
Because there is non-braking space, even it is not visible for naked eye, it is still a character. There are many other similar characters which are not visible for the eye, but can be still present in the string. Therefore it would wrong for the keyword to treat non-braking space or any other white space as regular space.

But there are solutions to your problem, because [assertions](https://marketsquare.github.io/robotframework-browser/Browser.html#Assertions) can be performed in many ways. The correct way depends what is important in the string, but perhaps doing regex would be easiest choice. Something like this could work:
```
Get Text    id=main    matches    Hello\\s\\sSpace
```
In any case this is not bug in the library and I am going to close the issue. If you need further assistance, please do not hesitate ask from our community: https://robotframework.org/#community In that you will most like get faster are more accurate responses.

**Comment by tomekTieto** [comment]
I know that issue is closed but maybe we should consider to add a bit similar argument for Get Text like we have in Should Contain - **collapse_spaces**. It could process string before assertions by replacing all whitespace characters with space character. It will really make our work easier 😃 

from BuiltIn.py:

`        If ``collapse_spaces`` is given a true value (see `Boolean arguments`) and both
        arguments are strings, the comparison is done with all white spaces replaced by
        a single space character.`
