### ISSUE TITLE
Run on failure does not work correctly if named argument syntax is used

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#1396]
**Describe the bug**
Run on failure does not work correctly if named argument syntax is used in keywordxs args. 

Originally reported in [here](https://github.com/MarketSquare/robotframework-browser/issues/1356#issuecomment-944088245) 

User are experiencing an issue:
```
[ WARN ] Keyword 'Take Screenshot ('fullPage', True)' could not be run on failure: 'tuple' object has no attribute 'upper' same with all possible arguments.
```

Tested on my local Windows environment and on browser-docker image.

**Comment by tomekTieto** [comment]
Hello @aaltat,
Looks like it still not working correctly for **filename** argument. All others are fine.
Try with:
`Register Keyword To Run On Failure  Take Screenshot  filename=robotframework-browser-screenshot-{index}`
It's failing because:
`Keyword 'Take Screenshot    filename=robotframework-browser-screenshot-{index}' could not be run on failure:
take_screenshot() got multiple values for argument 'filename'`
Working fine for positional argument.
Checked on version 11.1.1

**Comment by aaltat** [comment]
Interesting, could you raise an issue about with `--loglevel trace` attached, so that we do not forget it.

**Comment by tomekTieto** [comment]
done https://github.com/MarketSquare/robotframework-browser/issues/1702
