### ISSUE TITLE
Add external libraries to docker image

### ISSUE THREAD

**Issue by DKryczka** [MarketSquare/robotframework-browser#1506]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to use browser library docker image, but it is missing some external libraries.

**Describe the solution you'd like**
Can you add this libraries to docker image?
- FakerLibrary
- ImapLibrary2

**Comment by aaltat** [comment]
We would like to keep our image as slim as possible and therefore we are not going to add aextra modules in it. Also it will be endless list of modules, because different users have different needs. 


The good side of docker is that you can use our image as a base and  aeasily add your own modules on top of it. For more details see https://docs.docker.com/get-started/

**Comment by DKryczka** [comment]
Thank you for information
