### ISSUE TITLE
Only one screenshot per log is saved

### ISSUE THREAD

**Issue by tuxmux28** [MarketSquare/robotframework-browser#175]
**Describe the bug**
Only one screenshot is saved per log: TESTCASENAME_FAILURE_SCREENSHOT.png and the screenshot is not directly visible in the log file (just the link).

**To Reproduce**
1. Run a testsuite with failing testcases.
2. Open the log :)
3. Rerun the testcases with the same log directory

**Expected behavior**
- For every failed teststep a screenshot is saved and displayed in the log.
- Existing screenshots are not overwritten.

**Comment by mkorpela** [comment]
@all-contributors please add tuxmux28 for testing

**Comment by xylix** [comment]
@tuxmux28 We considered a couple options with @mkorpela . Would a fine solution be to create a unique screenshot directory per run (so for example on library init we create a folder named <timestamp>-testrun-screenshots) and then save the screenshots in that? This would allow grouping of screenshots for a test run since they would be in the same directory.

**Comment by mkorpela** [comment]
So this would be inside of the output dir.

**Comment by tuxmux28** [comment]
A unique screenshot directory would be great 👍

**Comment by xylix** [comment]
This is now fixed with c58de6164e02f2d53f1c56bed3b55892377c5251 . We added rolling indexing to default failure screenshot filenames and optional SL style `{index}` replacing with rolling indice in custom filenames.
