### ISSUE TITLE
Get Checkbox State always returns "unchecked"

### ISSUE THREAD

**Issue by zastress** [MarketSquare/robotframework-browser#1767]
**Describe the bug**
When using the `Get Checkbox State` keyword, the result is always unchecked.
Tested on Browser library version 11.4.0 but also reproduces on earlier versions

**To Reproduce**
```
*** Settings ***
Library    Browser

*** Test Cases ***
Test
    New Browser    headless=False
    New Page    https://demo.applitools.com/
    Wait For Elements State    //div[@class="form-check-inline"]/label
    Check Checkbox    //div[@class="form-check-inline"]/label
    Sleep    2s
    Take Screenshot
    Get Checkbox State    //div[@class="form-check-inline"]/label    ==    checked

```
** Error **
`Checkbox //div[@class="form-check-inline"]/label is 'False' (bool) should be 'True' (bool)`

**Additional context**
- Added an example test case after I saw the behavior in my project
- We know that Playwright gets the checkbox state right because `Check Checkbox` and `Uncheck Checkbox` work correctly.

**Comment by aaltat** [comment]
@allcontributors please add @zastress for bugs.

**Comment by zastress** [comment]
@allcontributors, can you please update my info with name instead of github username in the contributors tab? I made the update after you added me last time :). Please add "Liviu Avram" instead of "zastress"
Thanks.

**Comment by aaltat** [comment]
The xpath selector is wrong, it does not point to the input element. It points to the label element which is not checked. It is interesting that selecting the checkbox works with the label (and I do not know why it works), but we pass the selector as is to Playwright side and it takes care of the element interaction.

Because all works, mostly, as expected, I am going to close the issue.
