### ISSUE TITLE
New Page keyword not working, gives a "TimeoutError: page.goto: Timeout 10000ms exceeded"

### ISSUE THREAD

**Issue by akhilPanickerJPL** [MarketSquare/robotframework-browser#1902]
New Page keyword not working, gives a `TimeoutError: page.goto: Timeout 10000ms exceeded`

**Steps to reproduce the behavior:**
1. Keyword used - `New Page    https://www.amazon.in/`
2. Run the robot script
3. See error (log file attached)

**Expected behavior**
New browser page should open
Note - `Open Browser` keyword works fine (for chromium and webkit. Firefox does not work, have raised a separate ticket with details).

**Screenshots**
![image](https://user-images.githubusercontent.com/100908567/159950275-6ec61a7b-10c7-4b69-801b-3f44149b198b.png)
![image](https://user-images.githubusercontent.com/100908567/159950511-22944e6a-39c9-41be-9d4f-08fa3128500a.png)

**Desktop:**
 - Windows 10

**Additional context**
Tried this with and without the setting `Suite Setup         New Browser    browser=chromium    headless=False`
Got same error in both cases.
[playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/8342903/playwright-log.txt)

**Comment by aaltat** [comment]
Yes, the page did not load according the both logs. There is many reasons why this could happen, example you have proxy which needs to be configured or something else. But 99% of the time, this is related something in your environment and general fault in Browser library. Also I did try `New Page    https://www.amazon.in/` in my test and all works OK for me.

Because of the above, I am going to close the issue. If you think that there fault in Browser library, please provide and example which we can run and demonstrates the problem.

**Comment by Sathish787** [comment]
Could you re-open this issue. 
I am getting same issue as stated. In order to get this issue, try open browser and context one time and execute each test in new page. Repeat the test suite for atleast 5 times. Then, you will be error as we get.
Log shows only failure/error of next step but not showing actual failure.
On my close observation, I noticed new page gets disconnected in few seconds and hangs till timeout.


![image](https://user-images.githubusercontent.com/22374311/180819672-1a917ab7-44d7-4a58-9158-9d2842cbd27e.png)
