### ISSUE TITLE
Link to issue tracker gives 404 when clicked from release notes

### ISSUE THREAD

**Issue by VilleSalonen** [MarketSquare/robotframework-browser#1942]
**Describe the bug**
When clicking link to issue tracker in release notes I get 404 page. URL is incorrectly encoded.

**To Reproduce**
1. Go to https://github.com/MarketSquare/robotframework-browser/releases/tag/12.3.0
2. Click on issue tracker link
3. Incorrect URL is opened: https://github.com/MarketSquare/robotframework-browser/milestones%3Av12.3.0

**Expected behavior**
Slightly better: correctly encoded URL is opened: https://github.com/MarketSquare/robotframework-browser/milestones/v12.3.0

Even better fix:

Use link directly to the closed issues of a milestone so user won't need to click Closed tab: https://github.com/MarketSquare/robotframework-browser/issues?q=milestone%3Av12.3.0+is%3Aclosed

**Comment by aaltat** [comment]
Thanks you, I did not see that. Fixed.

**Comment by laurihelkkula** [comment]
This problem seems to be present also in other places:
- All release notes (that include the issue tracker link, most likely since 12.0.1) in the GitHub Releases pages except for 12.3.0. For example, https://github.com/MarketSquare/robotframework-browser/releases/tag/v13.3.0
- All (or at least most) release notes in https://github.com/MarketSquare/robotframework-browser/tree/main/docs/releasenotes
  - These notes include two issue tracker links. It seems that the first one is broken and the second one works (but doesn't include the closed filter).
