### ISSUE TITLE
Add support for retain-on-failure in tracing and videos

### ISSUE THREAD

**Issue by neslinesli93** [MarketSquare/robotframework-browser#2007]
As the title says, it would be awesome to have support for `retain-on-failure` config for traces and videos, as the docs says:
- https://playwright.dev/docs/test-configuration#record-video
- https://playwright.dev/docs/test-configuration#record-test-trace

Since the tracing results as well as videos are a huge mess of filenames with hashes, it would be great to just have them for failing tests, as playwright already seems to support

**Comment by aaltat** [comment]
There is support on Playwright Test which is an test automation framework, but this library doesn't use Playwright Test. Instead we are using Playwright API/Library from the node side and therefore we can not use Playwright Test functionality.

Video support currently is far from good and example we have #1747 to enhance it. The issue also explains what is problematic on the request. We are open on enhancement requests/ideas, but the problem doesn't have simple solution. Please give your ideas in #1747 

But because we can implement this feature request, therefore I will close this issue.
