### ISSUE TITLE
"New Context" and "New Persistent Context" keywords should always return a Path-object with full video path in recordVideo dictionary

### ISSUE THREAD

**Issue by ssallmen** [MarketSquare/robotframework-browser#2215]
**Is your feature request related to a problem? Please describe.**
At the moment it depends on whether the directory given in the dictionary as recordVideo argument already exists or not, whether the `New Context` keyword mutates the dir-key value to a Path object, or does it keep it as a string. That makes things inconsistent.
Even more inconsistent is that `New Persistent Context` keyword never mutates the dir-key value of the recordVideo argument dictionary but keeps it untouched, even when user has given a relative path. `New Context` keyword will mutate the dir-keys value with the full path as Path object if the path given by user did not exist, or if the given path was relative.
There is also another bug in `New Permanent Context` keyword related to the video recording which I reported separately in https://github.com/MarketSquare/robotframework-browser/issues/2214

**Describe the solution you'd like**
Both `New Permanent Context` and `New Context` should always "return", independent whether the path was existing or not or if it was relative or absolute, the full path either as a Path-object or as a string as the value of the dir-key in dictionary given as recordVideo argument.

**Additional context**
I have code already prepared for the change (always returning Path-object as that's what we discussed with @aaltat). Maybe some tests need to be added to make that a PR.

**Comment by Snooz82** [comment]
`New Page` does return the Path to the video file of that particular page.
`New Context` without a page has no video, so it does not help to return that.

`New Persistent Context` will return a tuple of `browserId` , `contextID` and `NewPageDetails` with 15.0.0

`NewPageDetails` is a dictionary that contains the keys `page_id` and `video_path`

**Comment by ssallmen** [comment]
@Snooz82, nice to see that you have done good enhancement for the `New Permanent Context` keyword but I am not sure if you fully understood the issue in `New Context` keyword, as it was a bit complex to explain. By "return" I did not mean the return value of the keyword but the mutation of the recordVideo dictionary values, as I tried to explain in the beginning of the ticket description: 

> At the moment it depends on whether the directory given in the dictionary as recordVideo argument already exists or not, whether the New Context keyword mutates the dir-key value to a Path object, or does it keep it as a string.

I don't know if that issue has been fixed already as it has been a while when I created the ticket, and many releases have been made, but my opinion is that the `recordVideo.dir` should be always handled the same way (i.e. mutated to a Path or kept as a string) independent on whether the path given as the value of `recordVideo.dir` already existed or not. It is a bit different bug than what is now fixed with that PR, and that PR should not close this ticket.

**Comment by Snooz82** [comment]
You are correct that is not yet solved.

I did not yet get it completely.
We removed the `videoPath` argument now.

So the only way is now the `recordVideo` dictionary.

the rules of the paths have changed a bit and are now:

1. if no path is given, videos are stored under `${OUTPUT_DIR}/browser/video`
2. If a relative path is given, it is relative to the path in 1.
3. If an absolute Path is given, it is stored there.


So are you talking about the resulting paths in Browser Catalog? `Get Browser Catalog`

**Comment by Snooz82** [comment]
Can you describe some reproducible cases and the effect to the users?

where is the difference between a path object given or a string?

**Comment by aaltat** [comment]
@allcontributors please add @ssallmen for bugs

**Comment by Snooz82** [comment]
@ssallmen 

I have now implemented it so, that the path will always be a resolved and absolute Path.

```    
def _set_video_path(self, params: dict) -> dict:
        record_video = params.get("recordVideo", {})
        video_path = record_video.get("dir")
        if not record_video:
            return params
        if video_path is None:
            vid_path = self.video_output
        elif Path(video_path).is_absolute():
            vid_path = params["recordVideo"]["dir"]
        else:
            vid_path = self.video_output / video_path
        params["recordVideo"]["dir"] = Path(vid_path).resolve().absolute()
        return params
```

**Comment by ssallmen-pro** [comment]
@Snooz82, this comment in another bug report explains the best how it used to work earlier, and what were the impications for the user: https://github.com/MarketSquare/robotframework-browser/issues/2206#issuecomment-1196938119
I have now created couple of test suites and ran them using the latest release (14.4.1) of Brower library available in PyPi, and found out that the behaviour has changed at some point so that the recordVideo.dir will always be string, independent on whether the path is absolute, relative, existing or non-existing. And that holds now true with both `New Context` as well as `New Persistent Context`. That is very good thing.
I am attaching [here](https://github.com/MarketSquare/robotframework-browser/files/10368757/new_context_tests.zip) couple of Robot test suites I just created for a sample, and a Python library which helped me with validating the types as with Robot handling variable types is a bit challenging. I was not able to run the same tests using teh version I used at that point (most probably 13.2.0) as for some reason the grpcio version (1.47.0) required by that version of Browser library did not install on the laptop I have at hand now. But that does not matter anymore. This issues seems to be fixed now even with the current released version.

**Comment by Snooz82** [comment]
@ssallmen @ssallmen-pro 

Ok now i understand the issue.
Yes. ok.

I used your tests and all pass.
The original dictionary is not changed/mutated anymore.

If it contains a string, it stays a string, if it contains a Path object it stays a Path object.

**Comment by Snooz82** [comment]
@allcontributors please add @ssallmen for tests
