### ISSUE TITLE
The source file of New Context in the documentation is wrong

### ISSUE THREAD

**Issue by mardukbp** [MarketSquare/robotframework-browser#2382]
**Describe the bug**

In the documentation generated with libdoc (in JSON or libspec format), the source file for the keyword New Context is `Browser/utils/deprecated.py`.

**To Reproduce**

1. Execute `libdoc Browser browser.json`
2. Search for "name": "New Context" and then for "source": 

**Expected behavior**

The source of the keyword New Context is `Browser/keywords/playwright_state.py`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103

**Smartphone (please complete the following information):**

**Additional context**

The keyword New Context has the following definition

```python
@keyword(tags=("Setter", "BrowserControl"))
@attribute_warning(
    old_args=("videosPath", "videoSize"), new_args=("recordVideo", "recordVideo")
)
def new_context(
    self,
    ...
)
```

Apparently, libdoc expects that the line after the keyword decorator is a function definition.

**Comment by aaltat** [comment]
Thank you for reporting problem, the bug most likely relies on the PLC side and I raised issue also there. 

@allcontributors please add @mardukbp for bugs.

**Comment by d-biehl** [comment]
After some investigation from my side, maybe it's not a problem of BrowserLibrary, I think it is more a problem of PythonLibCore.

Your `attribute_warning` decorator uses functool.wrap to but it is not handled in PythonLibCore

This line https://github.com/robotframework/PythonLibCore/blob/ef35336fbc895d3d329a6d61be52501c2a5a54d4/src/robotlibcore.py#L142 must unwrap the method using `inspect.unwrap` like this. And maybe it should also use `inspect.getsourcefile` instead of `inspect.getfile` because `getsourcefile` returns only returns sources not compiled files

**Comment by d-biehl** [comment]
changing the given line to 

```
return os.path.normpath(inspect.getsourcefile(inspect.unwrap(method)))
``` 

should do the trick and it is also the same like robotframework gets the source for a keyword.

**Comment by aaltat** [comment]
sorry for delayed answer. 

Could you provide PR in the PLC side?

**Comment by aaltat** [comment]
This should be now fixed in PLC side, closing this issue too.

**Comment by aaltat** [comment]
New PLC will be used in next release #2412
