### ISSUE TITLE
Is there any way we can use both libraries together such as Selenium and Browser library in a single script?

### ISSUE THREAD

**Issue by everlighting** [MarketSquare/robotframework-browser#2387]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaltat** [comment]
It's not possible to mix keywords from SeleniumLibrary and Browser library and control the same browser. Also this functionality will never be possible in the seen future. 

This is because SeleniumLibrary uses Selenium to control the browser and Selenium uses the WebDriver to control the browser.  Browser library uses Playwright to control the browser and Playwright is based on the chrome devtools protocol. Because of the two different technologies, one can not mix the keywords from SeleniumLibrary and Browser library. 

Because we can not fulfil your need, I am closing this issue. 

For future: Next time it's better to describe your need also in the issue body and not only in the heading.
