### ISSUE TITLE
Tracing enabled for None 

### ISSUE THREAD

**Issue by tomekPawlak** [MarketSquare/robotframework-browser#2520]
**Describe the bug**
Looks like a **None** str is incorrectly converted to Python **None** object when using named argument **tracing** in **New Context** keyword. **None** becomes a name of the tracing ZIP file.

**To Reproduce**
Two code snippets

This one will create **None** file 
```
Tracing is None
    New Browser
    New Context  tracing=None
    New Page  https://www.google.com/
```
This one using builtin variable will work fine
```
Tracing is ${NONE}
    New Browser
    New Context  tracing=${NONE}
    New Page  https://www.google.com/
```

**Expected behavior**
None (str) should be converted to Python None (obj) and therefore tracing should be disabled.

**Desktop:**
 - OS: Windows 10
 - Browser Chrome Version 108.0.5359.125
 - Library Version 14.1.0

**Comment by aaltat** [comment]
The Browser library relies on RF to make the [type conversions](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-conversions) automatically and the converting `None` is actually quite problematic when arguments accepts `None`and `str`. There is [issue](https://github.com/robotframework/robotframework/issues/4090) about the problem and I think there are several other issues too in RF issue tracker for the same problem if you want to dig deeper.  Currently the current functionality is actually correct, which is somewhat annoying for the users. 

The good news is that when we raise minimum required RF to 5.0.1 we can use custom converters (read the whole chapter in [User Guide](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#specifying-argument-types-using-keyword-decorator)), which will help to solve this and few other similar problems easily.  Unfortunately we also support RF 4.x but perhaps after RoboCon we can raise the minimum required RF version and also fix this problem.

**Comment by aaltat** [comment]
@allcontributors please add @tomekPawlak for bugs

**Comment by Snooz82** [comment]
@tomekPawlak 

This is a feature and not a bug.
Not necessarily with `tracing` but on other arguments that accept `<str>` or `<None>` , if all `none` strings would be converted to Python `None` (NoneType), it would not be possible to hand over a string `"none"` 

The actual problem i see here:
in Libdoc HTML it looks like the default is `None` but it is actually `${None}` 
This information is already missing in Libdoc JSON and i would consider that a bug in Robot Framework.

Because we can not do anything here, i will close that issue
