### ISSUE TITLE
Keyword "Fill Secret": Too tight/incomplete coupling with CryptoLibrary

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#2536]
I want to propose a small change to `decrypt_with_crypto_library`, used by the keyword `Fill Secret`:

https://github.com/MarketSquare/robotframework-browser/blob/65f33af20e0ae66214384581c4d2e43172d9f3df/Browser/base/librarycomponent.py#L168-L189

The problem in the code above is that in line 173, the `CryptoUtility` object gets created with _default values_: On Windows, the default key_path is set to  `C:\Program Files\Python38\lib\site-packages\CryptoLibrary\keys` ([src](https://github.com/Snooz82/robotframework-crypto/blob/502196c3319907570ea504e12c6bd717f59c2441/src/CryptoLibrary/utils/cryptoutility.py#L41-L43)) 

I (and perhaps others, too) am relying on the CryptoLibrary's API which allows to **specify a custom path for the key pair** during import (I personally dislike to store keys inside the Python library structure): 

```
CryptoLibrary  password=%{ROBOT_CRYPTO_KEY_PASSWORD}  variable_decryption=True  key_path=${CURDIR}${/}keys
```

But then Browser Library fails with 

`[FAIL] ValueError: key_path: "C:\Program Files\Python38\lib\site-packages\CryptoLibrary\utils\../keys/" is not a valid directory!`

because the directory and the keys are at a custom location and not the default one. 

---

My proposal is

- First, try to only _import_ `CryptoUtility`
- if it fails, just return the secret - perhaps the secret isn't an encrypted string at all
- Then do a regex comparison against the `CIPHER_PATTERN` in CryptoUtiity's _class_ (not the object!)
- If the user really handed over a `crypt:....` string, then - and only then - CryptoUtility should be created as an object. 

```python
    def decrypt_with_crypto_library(self, secret):
        if self._crypto is None:
            try:
                from CryptoLibrary.utils import CryptoUtility  # type: ignore
            except ImportError:
                return secret
        if (
            isinstance(secret, str)
            and re.fullmatch(CryptoUtility.CIPHER_PATTERN, secret)
        ):
            try:
                if self._crypto is None:
                    self._crypto = CryptoUtility()
                plain_text = self._crypto.decrypt_text(secret)
                logger.trace("Successfully decrypted secret with CryptoLibrary.")
                return plain_text
            except Exception as excep:
                logger.warn(excep)
                logger.trace(traceback.format_exc())
        else:
            return secret
```

---

If I may say so...  I was astonished when I saw in the code that the browser library uses mechanisms of the CryptoLibrary under the hood. 
For the normal user this is almost impossible to understand, because the documentation of the Browser Library does not contain a reference to the utilization of the CryptoLibrary anywhere. 
My gut feeling (please correct me if I am wrong) is that this is only half implemented. What problem should be solved with the integration of CryptoLibrary features?

**Comment by Snooz82** [comment]
@allcontributors please add @simonmeggle for ideas

**Comment by Snooz82** [comment]
@simonmeggle Thanks for you comment.

Yes. it is now (will be) documented in the 15.0 release.

Regarding your idea, i agree, that this code could be optimised a bit.

1. if anyone handing over `crypt:somethingsomething` to `Fill`/`Type Secret` that will fail, if there is no Crypto Library.
  Because we removed now the long time deprecated behaviour, that these Keywords just spit out a warning, if real values are given.
2. I do not see how your proposal really changes the behaviour.
  i totally agree, that i missed to "use" the arguments that are possibly given to CryptoLibrary when imported to Robot Framework, but you did as well. So how does that fix the bug?
  
My Proposal would be to first try to import, then retrun on exception, check the crypto pattern, **then try to get the CryptoLibrary instance from Robot Framework**, if fails, try to instantiate it, try to decrypt.

I think with that you can import CryptoLibrary and give it arguments and Browser could still use it.

**Comment by simonmeggle** [comment]
@Snooz82 Thanks for your response. 
I totally agree, my proposal is not a complete solution. It was rather meant as a first draft to make the code not crash...

But I still don't get the reason why Browser Library also should care about the decryption of secrets. 
I think the main task of `Fill Secret` is to do what its name tells: enter the value and hide it from the logs, nothing more.
