### ISSUE TITLE
Assertion only compares leading number

### ISSUE THREAD

**Issue by Finalrykku** [MarketSquare/robotframework-browser#273]
I just found a very strange behavior because a test succeeded which should fail.
Assume there is a tag 
`<div id="test">4</div>`
If I execute
`Get Text    \#test    >=     123`
What should be the expected result be? I got ${RETURN_VALUE} => 4
The same goes for
```
Get Text    \#test    >=     223
Get Text    \#test    >=     323
```
But not if there is a leading 4 or greater. The assertion operator only compares the leading number. 
`Get Text    \#test    >=     4`
is fine
Is this on purpose? :open_mouth:

**Comment by aaltat** [comment]
Yes, this is expected result and correct. Remember that you are comparing strings and not numbers. In Python `"234" < "4"` evaluates as `True`, which is surprising, but correct in Python.

Although above is correct in Pythonic way, it's not very usable as a keyword functionality. But it's very hard problem to solve, because there are plenty of numerical presentations and it's hard to know when string should be converted as a number (and which type of number) and when that should not be done. 

We need to think is there good way to solve the problem.

**Comment by Snooz82** [comment]
If you want to compare numbers, you can use validate.

`Get Text    \#test    validate    value >= 323`

**Comment by aaltat** [comment]
Ah we did already have solution, did not remember that one. Thanks for reminding us @Snooz82

**Comment by Finalrykku** [comment]
Ah yes ok. Thank you!
