### ISSUE TITLE
Add support for RF 6.1 

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#2785]
Add support for RF 6.1, this at least causes issue https://github.com/robotframework/robotframework/issues/4538

**Comment by pekkaklarck** [comment]
The underlying issue has been there since RF 6.0 when we started to convert itens inside generics like `list[Permission]`. That affected usages like `permission=['xxx']` where the container is specified as a literal. The fix in RF 6.1 changes the behavior so that conversion is done also if the container is an actual list, dict, etc. In other words, this fix actually makes Browser RF 6.0 compatible.
