### ISSUE TITLE
Wait For Response, no way to specify modifiers when using regex for the matcher?

### ISSUE THREAD

**Issue by nathanhannig** [MarketSquare/robotframework-browser#2822]
The documentation for Wait For Response says a matcher can be specified as a JavaScript regex; this means I should be able to provide a modifier as part of the regex such as global search or insensitive search.

It looks like the matcher option does not allow you to provide these modifers?

**Comment by Snooz82** [comment]
@allcontributors please add @nathanhannig for bugs

**Comment by Snooz82** [comment]
This is a correct report.

These keywords did always just figure out if there is a js function else create a RegExp object from string.
Therefore everything that was not a function was a RegExp without the required slashes before and after.
And without the possibility to define flags.

that will be fixed, but is a backwards incompatible change.
This may actually cause some trouble out in the field.

This fix however is, to just add a / before and after the previous regex string.

Will be fixed by #2927
