### ISSUE TITLE
'Get Element By' cannot get element locator in iframe

### ISSUE THREAD

**Issue by RatexMak** [MarketSquare/robotframework-browser#3019]
Project does not have frame_locator keyword. It seems, therefore, 'get element by' or 'get element by role' keyword cannot function in iframe. Would it be posible to have frame_locator back or 'get element by'/'get element by role' keyword could take frame selector as an input value.

eg:  translate python code below into robotframework programe
```python
page1.frame_locator("iframe[name=\"pdiv_page-mainIframe\"]").get_by_role("button", name="apply").nth(0).click()
```

**Comment by aaltat** [comment]
So you want to pierce frame with example `Get Element By Role` keyword. At least we are lacking acceptance tests on the matter.  So in practice, in RF syntax, you would like something like this to work: 

`Get Element By Role    textbox    name=right >>> name=searchbutton`

This could be tricky to implement, but might be possible.

**Comment by aaltat** [comment]
@allcontributors please add @RatexMak for ideas

**Comment by aaltat** [comment]
I did try it out and frames are not supported currently: https://github.com/MarketSquare/robotframework-browser/pull/3022

**Comment by RatexMak** [comment]
Thank you for noticing this problem! It's of great help if it get fix in the future. 
As a newbie of coding, I would also try to look into the source code.
GRPC was used in 'get element by' / 'get element by role' keyword, and maybe we should try out other conditions for the input value of GRPC.

**Comment by aaltat** [comment]
I don’t follow your comment about GRPC, could you clarifying it (I know what GRPC is and how it’s used in this library)?

**Comment by RatexMak** [comment]
I am no sure if I am right. But does the code here seem to established a gprc connection for getting element by specific condition?
![image](https://github.com/MarketSquare/robotframework-browser/assets/33491425/80604b4f-88d1-43e0-8e11-755e2225ffa6)

**Comment by aaltat** [comment]
Yes, library uses GRPC, because that is the library architecture: Python <-> GRPC <-> Playwright (NodeJs). Python side exposes keywords in the Robot Framework side, but Playwright in NodeJS controls browser, context and many other stuff related to the Playwright API. and GRPC is used to communicate between the Python and NodeJS worlds. 

But I am still unclear what you mean which your comment.

**Comment by Snooz82** [comment]
At the moment it just calls `activePage.getByRole(text as AriaRole, options);` therefore it does not support frames.

The proposed syntax is imho not a good approach, because it adds more magic.

We could add an additional argument `frame_selector` or so, but i would actually postpone that or just not support it.
However, if the argument `frame_selector` is set, the frame is taken as start.

```
Get Element By Role    textbox    name=searchbutton    frame_selector=iframe[id='frame']
```

**Comment by Snooz82** [comment]
It is now implemented differently.

`Get Element By Role` and `Get Element By` does now respect the set selector prefix by `Set Selector Prefix` if this does select an iframe.

See #3221
