### ISSUE TITLE
Browser wrapper process does not terminate preventing playwright log file deletion

### ISSUE THREAD

**Issue by apvilkko** [MarketSquare/robotframework-browser#3090]
**Describe the bug**
playwright-log.txt file can not be deleted. Deletion attempt results in "File In Use" Windows dialog stating that "The action can't be completed because the file is open in Windows Command Processor".

Monitoring processes in Windows Task Manager reveals that for each test run a new cmd.exe process is spawned with the command line: "cmd.exe /C node C:\path\to\project\env\lib\site-packages\Browser\wrapper\index.js", and a corresponding node.exe process.

Only by manually ending the aforementioned cmd.exe and node.exe tasks can the playwright log be deleted.

**To Reproduce**
- Create a simple test of opening an url and checking h1
- Run the test with "robot"

**Expected behavior**
No spawned processes remain hanging after test run and all produced log files can be deleted.

**Additional context**

- Windows 10
- Windows Terminal (seems to be irrelevant, same thing happens in cmd.exe)
- Python 3.8.10 with virtual environment
- robotframework 6.1.1
- robotframework-browser 17.4.0
- node 18.17.1

**Comment by aaltat** [comment]
@allcontributors please add @apvilkko for bugs

**Comment by aaltat** [comment]
I agree that library should work in the way you want. We actually have code that registers https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/playwright.py#L58 close method https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/playwright.py#L167 which should ensure that process is killed when Python closes. But windows is problematic OS in many cases and closing process may not possible because handle is open somewhere or some other similar problem. Basically the point is that it may not possible, in Windows, to close the node process while the Python process from RF is still running. 

In many cases it is easier to write a runner script which will make sure that node process is terminated after test case execution is done. 

The thing which we could consider to change is that if opening the `playwright-log.txt` file fails, we would create a new file but with unique file name.

**Comment by apvilkko** [comment]
> In many cases it is easier to write a runner script which will make sure that node process is terminated after test case execution is done.

Here's a Python snippet of what I did as a workaround (you may need to modify the path of the Browser wrapper to match your setup):
```
import sys
import os

# ... test run here

# kill hanging processes on Windows
if sys.platform == 'win32':
    os.system("wmic Path win32_process Where \"CommandLine Like '%site-packages\\\\Browser\\\\wrapper%'\" Call Terminate")
```

**Comment by aaltat** [comment]
I am closing this on favor of #2968

I don’t see a way which would fix this problem in the library side. But in #2968 we can implement of not creating the long file and/or appending a random part so that file will be always unique.
