### ISSUE TITLE
Accessibility testing library with Browser?

### ISSUE THREAD

**Issue by qasamppa** [MarketSquare/robotframework-browser#3293]
**Is your feature request related to a problem? Please describe.**
Accessibility testing axe-core library from Playwright
https://playwright.dev/docs/accessibility-testing
Is this possible to install and bring these keywords visible to Robot?

**Describe the solution you'd like**
What would be best solution for accessibility testing by using Browser library?

**Describe alternatives you've considered**
There is one axe-core-python library but not so lately updated.
https://pypi.org/project/axe-core-python/

**Additional context**

**Comment by aaltat** [comment]
Technically you can build it already with plugin and js extension. You need to install axe-core to same directory where we install Playwriting and you should be ready to go for implementation.

This is actually good idea, but because it steps outside of the Playwriting, I don’t think it is suitable for the Browser library. But I know that there is community that builds extensions for Browser library and for there this would be perfect match.

**Comment by aaltat** [comment]
Example in this project https://github.com/MarketSquare/robotframework-browser-extensions

In any case, I am closing this issue, because this is not implemented in this project.
