### ISSUE TITLE
Codegen for BrowserLibrary

### ISSUE THREAD

**Issue by roydekleijn** [MarketSquare/robotframework-browser#3495]
Have you thought of bringing codegen for BrowserLibrary ?

It would help new joiners to get started quickly.

I was about to fork and change the recorder for playwright, but that is not a neath solution... Wondering if you considered something like this

**Comment by aaltat** [comment]
We have tough about it, but because Robot Framework is more than playwright (which runs under the Browser library) the codegen approach used by Playwright is not suitable for us. But there are solutions available which which will yield to same or better results. Example one could use https://github.com/imbus/robotframework-debug/ and it's `irobot` tool with combination of Browser library `enable_presenter_mode` import setting, then I think one can better result than code generation tools.

Also we have gitpod file available in the repository, which can help user to get started. Also RF has https://robotframework.org/#getting-started and online editor available, although it does not have Browser library available.

But we understand that getting started with Browser library can be hard and we are open to new ideas. Would you have some ideas how to lower the barrier to getting started?

**Comment by aaltat** [comment]
Closing due inactivity.
