### ISSUE TITLE
Issue with Opening New Pages in Version 18.4.0

### ISSUE THREAD

**Issue by DylanKao** [MarketSquare/robotframework-browser#3588]
Hi Team,

We encountered an issue when attempting to open a new page. It appears to be non-functional in version 18.4.0, whereas it operates correctly in version 18.3.0. Do you have any insights into this problem? Thanks.
![image](https://github.com/MarketSquare/robotframework-browser/assets/13566870/04cf4a15-b444-4128-94e6-540eed64be44)
![image](https://github.com/MarketSquare/robotframework-browser/assets/13566870/d9f42657-664b-4e32-8944-c03f34e2d058)
![image](https://github.com/MarketSquare/robotframework-browser/assets/13566870/97ed0c60-8607-4971-a186-fc85a2a5e74c)

**Comment by aaltat** [comment]
After upgrading the Pythons package, did you also run the `rfbrowser clean-node` and `rfbrowser init` commands to update the node dependencies?

**Comment by DylanKao** [comment]
Hi @aaltat,

Yes, I added the `rfbrowser clean-node` and `rfbrowser init` commands before running the test, but it still failed when attempting to open a new page.
By the way, I'm using GitHub Actions for robot testing. I believe it's a completely new container without any cache issues.
Thank you!

**Comment by DylanKao** [comment]
Hi @aaltat 

I cannot display rfbrowser's version using --version or --verison commands, but the version should be the latest one, 18.4.0. Also, here is the debug log of playwright: [playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/15258914/playwright-log.txt). Please kindly review it. Thank you.

**Comment by aaltat** [comment]
Basically log is telling that page doesn’t load in 10 seconds:
```
at async PlaywrightServer.newPage (/usr/local/lib/python3.10/dist-packages/Browser/wrapper/index.js:10708:28) {
  name: 'TimeoutError'
 ```

Why the page doesn’t open is not revealed from the log and is an matter where I can’t help because I am not unfamiliar with your environment. 

The code in Browser library which controls opening pages has not changed between 18.3 and 18.4 releases. What has changed is the Playwright version, from 1.42.1 to 1.43.1 and with that the browser binaries have also been updated by Playwright, more details in https://playwright.dev/docs/release-notes I would guess that this might be reason for your problems.

**Comment by aaltat** [comment]
Closing because we in the Browser library are not able to fix this problem.
