### ISSUE TITLE
grpcio and protobuf are pinned to fixed versions, conflicting with existing env

### ISSUE THREAD

**Issue by iwanb** [MarketSquare/robotframework-browser#3615]
**Is your feature request related to a problem? Please describe.**
I would like to install robotframework-browser within an existing project which already depends on grpcio and protobuf. We use and need a specific version of grpcio and protobuf, but robotframework-browser pins to versions which are not compatible.

https://github.com/MarketSquare/robotframework-browser/blob/103a3fd056807f95a960aa90c81a09310192448f/Browser/requirements.txt#L1

**Describe the solution you'd like**
The version constraint of grpcio and protobuf should be relaxed, and only pinned at build time (e.g. in `requirements-dev.txt`). I also think `grpcio-tools` can be a build-time dependency rather than runtime, but I might have missed something.

Protobuf is unfortunately not very clear on what's the compatibility guarantees on compiled protobuf file, but it looks like `protobuf >= 3.19` has good backwards compatibility:
https://github.com/protocolbuffers/protobuf/issues/11123

A possibly more robust but more complicated solution is to compile the protobuf at install time, in `setup.py`.

**Describe alternatives you've considered**
I'm looking into rebuilding it myself against a different grpcio and protobuf version.

I've had my share of headaches with protobuf compatibility so I can certainly understand if you don't want to support multiple versions!

**Comment by aaltat** [comment]
Because library lives both in Python and nodejs land, what you ask of is not that straightforward. Because it would require managing both language dependencies and to support it, we would need to test every combination. That would blow up our CI matrix and cause lots of dependency problems.

But have you tough about installing RF and it’s dependencies in a virtual environment https://docs.python.org/3/library/venv.html

**Comment by iwanb** [comment]
I believe it interacts with nodejs using gRPC right? gRPC itself should be very much backwards compatible, so the versions on each side do not need to match. Of course I understand it still means more combinations to support/test.

For the venv, that's indeed what I do, but I want to use libraries which require a different gRPC version directly from robot tests, for that it has to be in the same venv.

Thanks for the answer!

**Comment by aaltat** [comment]
Without testing was can not provide support and gRPC is the main reason why our CI system is so big. Many times in the history Google has, for some reason or another, not made a release for certain OS and Python combination, but a combination we still support. Also we support the two latest LTS version of NodeJS. So when we calculate all this, we test with Python 3.8, 3.9, 3,11 and 3.12, there is three different OS versions and two NodeJS versions, so in to total is  +15 different build combination (we skip few). So if there is need to support, lets say last three or four latest gRPC versions. That will end up +50 different builds. All which can be done, but will cause some work now and more work with maintenance. The biggest problem increasing the builds is that it will significantly lover the experience on CI, because we run on free account on GitHub and resources on free account are limited. 

Letting users to compile the gRPC protocol is not the way one should go. Instead we should release build release for each support gRPC version. That would also mean that building should be moved to CI, which work and long term maintenance cost. Also moving build and release to CI has it benegits too. 

Also this open a door for more support, I can predict how much extra support this would bring, but at least there is a possibility for it.

The point I am trying to make is that there is more work than just changing line in the `requirements.txt` and the cost is not just one time, there is continues need for maintenance one way or another. Therefore from the project point of view the bang for the bug is not there, if there would be more request for this type of change, it could affect project decision. But as far I can recall, you are the first one to request this type of change. 

But your need is not without hope. If assumption from fRPC is correct, you after installing Browser library, you could just install the version of gRPC you want it might work. If it does not work, compilation of the protobuf is not complicated. And gRPC is pretty well isolated from the library. So if you compile it and replace it with the library one, it should work.

**Comment by iwanb** [comment]
I understand, thanks for the detailed response.

I see the pdm and uv package manager actually support overriding the requirement constraints of dependencies. So that can be a solution, leaving the burden to the end user to relax the constraints. Unfortunately I use poetry which doesn't support it, but I can edit the package instead as you suggested.

**Comment by aaltat** [comment]
Well, you could just run pip trough poetry (poetry run) and install the version you want. Little bit of a hack but should work fine.

**Comment by suiluj** [comment]
same problem here

**Comment by aaltat** [comment]
As you can see from the above discussion, what you want is not possible with the current resources available. The need grows the maintenance burden too big and would eat all resources available (remember that this project is not funded by companies and is done in maintainers free time, which is same for many projects in open source.) Therefore we have to decline your need in the foreseeable future.

If you need other version of protobuf and grpc than what this project supports and above mentioned workarounds do not work, then the way to go is to fork this project and create your own package. I understand that might not be optimal for you, but it’s not something impossible to do. We have documentation how we manage our development process and how package is built and published. Therefore doing your own fork and package is not hard.
