### ISSUE TITLE
Getting the error while installing Robot Framework browser library 

### ISSUE THREAD

**Issue by nagaraj0312** [MarketSquare/robotframework-browser#365]
[Browser.txt](https://github.com/MarketSquare/robotframework-browser/files/5154856/Browser.txt)
![browserscreenshot](https://user-images.githubusercontent.com/15028268/91826506-4dd1de00-ec5b-11ea-9b0c-cf641204019e.png)

**Describe the bug**
Getting the error while installing Robot Framework browser library  i have attached the screen shot and logs for the same

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaltat** [comment]
The error happens when pip download package from PyPi and it's not yet executing our library code. There are numerous reasons why the error could have happened, starting from your proxy or firewall configuration to random timeouts in the internet connection. 

Have you retried the installation and does it happen always? Does it happen with all the Python packages that you are trying to install with pip?

**Comment by nagaraj0312** [comment]
@aaltat  now i have tried it worked properly

**Comment by aaltat** [comment]
Because it works I am closing the issue.
