### ISSUE TITLE
An Expect keyword that makes use of the test assertions of the expect function of Playwright

### ISSUE THREAD

**Issue by falcon030** [MarketSquare/robotframework-browser#3874]
**Is your feature request related to a problem? Please describe.**
Playwright has [Auto-retrying assertions](https://playwright.dev/docs/test-assertions) for locators.  It would be nice if we can use.

**Describe the solution you'd like**
I would like to get a new keyword `Expect' which let you use these assertions. Example

```
New Page    ${URL}
Expect    ${SELECTOR_1}    to have count    2
Expect    ${SELECTOR_2}    to be visible

```

**Comment by aaltat** [comment]
We can not use [Playwright test](https://playwright.dev/docs/api/class-test) because it is actually a test runner, which does the same thing as Robot Framework. We can use Playwright API, like [browser](https://playwright.dev/docs/api/class-browser). That being said, we have [assertions](https://marketsquare.github.io/robotframework-browser/Browser.html#Assertions) which does a similar thing as Playwright test `Expect`. But quickly looking the docs  and code, you can not actually assert length. Which could be handy thing. 

If you need more assertions, like the length validation please raise an issue to the [AssertionEngine](https://github.com/MarketSquare/AssertionEngine/) project side. But because this is something we can not fix in this project, I am going to close this issue.

**Comment by aaltat** [comment]
Did forget to mention that element visibility can be asserted with [Get Element States](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Element%20States) keyword.

**Comment by falcon030** [comment]
@aaltat As far as I understand , these [assertions](https://marketsquare.github.io/robotframework-browser/Browser.html#Assertions) are not Auto-retrying assertions? It is possible to use the `expect` function of Playwright. You can do this by making a Robot Framework Browser Extensions and directly use the `expect' function by including the following code in the extension
```
const path = require('node:path');
const { expect } = require(path.resolve('node_modules/playwright/test'));

```
Now you can use the `expect` function in your JavaScript code.
But I think it would be nicer if it would be part of the Browser Library itself, instead of using an extension.

**Comment by aaltat** [comment]
Assertions in the library are doing retry always. By default and it’s different than the library timeout, it’s one second. Default can be changed by https://marketsquare.github.io/robotframework-browser/Browser.html#Set%20Retry%20Assertions%20For

**Comment by aaltat** [comment]
But because you are not the first one who thinks this way, would you have an improvement idea how to improve the knowledge?

**Comment by falcon030** [comment]
@aaltat My bad, I should have read the browser claims documentation more carefully. Still I had a case where `Get Title equals 
 ${page_title}` failed because it didn't wait for the new page to load. `Wait For Condition title` solved this problem. Just like the Playwright equivalent `expect(page).toHaveTitle`.
 I think that part of the problem is that the Locator and Page assertions of Playwright are easier to use. Just but expect() around your locator or page object followed by your desired assertion. With Browser Library you have different keywords that support assertions, or in some cases you have to use wait for condition or wait for element to accomplish the same. Also Playwright supports more assertions then Browser Library does at this moment.

**Comment by aaltat** [comment]
Do not worry, that it pretty well hidden gem and we should make it, someway, easier to users find it. Any good ideas? 

Yes, Playwright is better in this way, because their syntax is more uniform. Robot Framework is keyword based and things goes trough different keywords. Also our library has evolved and not all things are uniform to do (legacy cause problems, but I agree that one and only one obvious way would be better also in Browser library). There is nothing that stop making Browser library more uniform, expect time to do it (we are not funded my Microsoft where people are actually paid to do the Playwright.)

If you are missing something from Playwright API or you missing assertions, please raise an issue. Missing assertions go the [AsserstionEngine](https://github.com/MarketSquare/AssertionEngine) project The Playwright test things we can not implement (but you could request that Playwright would move some of the features to be available in Playwright API side.)
