### ISSUE TITLE
Support NodeJS 23

### ISSUE THREAD

**Issue by Houbein** [MarketSquare/robotframework-browser#3900]
I know this is not an "LTS", but I hate the LTS concept. NodeJS 24 does not gain LTS status untill november 2025 and I think it's a shame to delay implementing new technology just for this arbitrary label.

**Comment by aaltat** [comment]
We don’t officially support NodeJS 23 because the odd release numbers for NodeJS are short lived. But in other hands we should not have, as far I can recall, anything that would prevent its usage. 

That being said, officially it will not be supported. Mainly because it needs resources from the maintainers and we feel that those resources are better spent somewhere else.

Closing issue
