### ISSUE TITLE
Add browser and contex be available in the JS extension side

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#3903]
**Is your feature request related to a problem? Please describe.**
Add browser and contex be available in the JS extension side.

**Comment by aaltat** [comment]
Done in #3901

**Comment by rasjani** [comment]
Sorry for Q in here but is this a breaking change ? eg,  should js extensions  be updated  to get browser and context arguments too ?

**Comment by aaltat** [comment]
Not that I recall, but is something broken?

**Comment by rasjani** [comment]
I had js extension that exposed keywords that did not require browser,  context *or* page  to be available (some statistics collection) and those keywords cannot be called anymore after 19.0.0 release because of "Browser is closed".  Initially i thought the issue was because of missing new arguments messing up before but  the fix obviously was to get my stats before closing context & browser .. 

So at least there's behaviour change that's related to this (?) and seeing it was labeled for  v18.10.0 - i was slightly worried because i didn't see any mention about possible backwards compatibility (albeit, bump to 19 did highlight possible backwards incompatibility changes).

**Comment by aaltat** [comment]
This should not have been changed, but I guess it was. Can you create a separate issue and perhaps with an example that demonstrates the problem.
