### ISSUE TITLE
Can't clicked some covered objects

### ISSUE THREAD

**Issue by eldaduzman** [MarketSquare/robotframework-browser#396]
**Describe the bug**
in Some cases when the object is covered by other DOM elements browser can't click on it and it returns a gRCP 'to-be-sent trailing metadata size exceeds peer limit' error

**To Reproduce**
1. execute this script (also attached as bug.robot.txt):

```robot
*** Settings ***
Library     Browser
Documentation           just a suite :)

*** Variables ***

${baseurl}   https://www.waggel.co.uk
*** Test Cases ***
Login test :)
    [Documentation]           just a test :)
    Open Browser    headless=${False}
    Set Viewport Size    2000    2000
    go to    ${baseurl}

    Click    xpath=//*[text()='LOGIN']
```

**Expected behavior**
either:
1. object is clicked on and test passes - most preferred
[bug.robot.txt](https://github.com/MarketSquare/robotframework-browser/files/5231667/bug.robot.txt)
[playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/5231670/playwright-log.txt)

2. object is not clicked on but a proper message is received by robotframework

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 85

**Additional context**
in this script example the playwright error was 'element is outside of the viewport'
the same behavior is observed in my companies product where the error by playwright is 'element does not receive pointer events'

**Comment by aaltat** [comment]
I agree that error message could be better and `to-be-sent trailing metadata size exceeds peer limit` is not clear. Although it comes from playwright side, we could raise better error message in Python side. 

But your locator matches on multiple elements and the first element is hidden by other elements. Also it is not possible to scroll the element to view and therefore keyword fails because it can not click the element. Please choose a locator which points only to a one element. In the above example, example this could work: `xpath=(//*[text()='LOGIN'])[2]`

**Comment by aaltat** [comment]
Because this issue reports multiple things, but we fill not fix only one of them, I am closing this issue and we will improve the exceptions in #403
