### ISSUE TITLE
Drag and Drop by selecting an element + X/Y

### ISSUE THREAD

**Issue by sub0br** [MarketSquare/robotframework-browser#467]
I've been trying to migrate my tests to Browser Library (was using Selenium Library). However, I've got some problems while using the Drag and Drop options. It seems easier, and with more precision, to use the Selenium Drag and Drop where you must set the element + its destiny coordinates. The current options forces me to use the Drag and Drop by Coordinates, and it seems unstable even if I set an instruction to wait until the page is fully loaded.
What do you think about adding the "traditional" Drag and Drop option?
Thank you for your attention!

**Comment by mkorpela** [comment]
Thanks for the feedback!
Could you post an example where SL works better than with Browser lib?

**Comment by sub0br** [comment]
My system has a list where I need to move its items sideways to show some buttons. With the D&D of SL I just need to set the element list and its destiny coords, while on BL I need to find the element first by its coords. This is a problem for me because I work with a responsive screen system. I've tried the D&D where I need to select 2 elements, but it doesn't work.

**Comment by Snooz82** [comment]
@sub0br 

I wouldn’t like to implement a `Drag and Drop from Element to Coordinate`.
Because that can be done with the existing keywords.

However i also thing that the Mouse Movement relative to an element could be a very handy keyword.
So i implemented the following Keyword:
```robotframework
Mouse Move Relative To    selector    x=0.0    y=0.0    steps=0
```

This does move the mouse to a position relative to the center of an element.
With that your usecase should be implemented relatively easy.

```robotframework
Drag from center to the right
    Hover    id=draggable
    Mouse Button    down
    Mouse Move Relative To    id=draggable    x=30    y=0    steps=5
    Mouse Button    up
```

That could work.
It will be included in the next Release.

But: All drag and drop action do use the bounding box of an element to calculate the positions where to drag and drop.
Be aware that when you use the boundingbox you have to calculate the center of the boundingbox.

```robotframework
DragonDrop 🐉 
    Hover    id=draggable
    Mouse Button   down
    ${center}     Get BoundingBox    id=draggable    ALL    then    {'x':value['x'] + value['width'] / 2 + 30, 'y':value['y'] + value['height'] / 2}
    Mouse Move     &{center}   steps=10
    Mouse Button    up
```
