### ISSUE TITLE
Start/Stop video recording by keywords?

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#497]
First, thanks for your tireless efforts on this project.  +1

One request about the video recording functionality in 2.1.0: 
@mkorpela , in #148 you wrote about _"Add keywords to start and store video recording"_ as a solution. 
As far as I can see, the video recording functionality is switched on/off on the browser context. 

I recently worked with the [screencap library](https://pypi.org/project/robotframework-screencaplibrary/) and appreciated the keywords _"Start/Stop Video/Gif Recording"_. This is great for selectively debugging flaky headless tests when you want to see what's happening on certain steps within a test. 

I wanted to ask if there was a _decision_ not to implement Start/Stop keywords as suggested initially (in favour of a browser context solution) - or if this is something you are anyway going to implement soon? 

Thanks -  
Simon

**Comment by aaltat** [comment]
Library uses Playwright to record videos and Playwright controls the video recording on the context level. There is not more fine-grained stop/start methods available in the Playwright side.

**Comment by aaltat** [comment]
I see too options.

1) We request feature from playwright and wait until someone implements the feature. Then we can change our implementation to support it.
2) We change the implementation and record videos by some others way. But that is difficult because browsers can run headless and it might not possible to get it working. 

Either way, I don't see easy option to implement this one. I  would suggest that you make feature requests to Playwright side. 

Because of the above, I am closing this issue.

**Comment by simonmeggle** [comment]
Thanks for the clarification, Tatu!

Tatu Aalto <notifications@github.com> schrieb am Mi., 11. Nov. 2020, 19:21:
