### ISSUE TITLE
Extending Browser Library with JavaScript

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#513]
**Is your feature request related to a problem? Please describe.**
Many people have been asking questions about extending the library.
The extensions could benefit from being written with the same language as the project they are testing. This would allow sharing code and other technical stuff from the development.

**Describe the solution you'd like**
I do not have a ready made solution. This is just a discussion opener / facilitator and the ideas are from @aaltat , @Snooz82 and from several others.

**Comment by aaltat** [comment]
The feedback from SeleniumLibrary shows that many people build their own custom keywords on top the SeleniumLibrary in Python. Either they build new library which, one way or another, extend SeleniumLibrary or they use SeleniumLibrary plugin API to inject keywords to the SeleniumLibrary.

There are many reasons to build custom keywords on top of the existing ones, example there might be custom date picker, which logic is hard to (or at least hard to read) do in Robot Framework data or other similar logic (custom for the user, like opening a browser, table keywords, custom elements which do not follow the HTML standards, drag and drop, mobile gestures) which does not exist in the SeleniumLibrary (and most likely will never be done in the SeleniumLibrary, because it is custom for that user.) 

The benefits that SeleniumLibrary has is that SeleniumLibrary and the underlying Selenium both live in Python. So when extending the SeleniumLibrary, it is easy to gain access to the Selenium WebDriver or WebElements and build custom logic by using SeleniumLibrary and/or Selenium API. Users are free to choose the API level which match their skills and needs.

Now with the Browser library, the Browser library lives in Python and node worlds and has [GRPC](https://grpc.io/) to communicate between the worlds. Users can extend the library in Python side, in same way as in SeleniumLibrary, but users are more limited (limited to the API and GRPC messages that we have build) because they do not have access to the node side. We do not have clear way to implement new GRPC protocol messages and there is not a way to implement new methods in the node side. I think, based on my gut feeling, many users in the SeleniumLibrary side use the Selenium API (at least partially, they might relay in SL to find elements, but they interact with he element directly) to implement the missing keywords.

**Comment by mkorpela** [comment]
One option I see would be to have a generic GRPC message for unsafe JS code execution on the node side in the playwright context (not the browser context). Something like:

```
class MyBrowser(Browser):
      def my_keyword(self):
            self.node_execute("""
(browser, context, page) => {
   page.tab("selector");
}
""")
```

**Comment by mkorpela** [comment]
I think even better would be to really import a foreign ts or js module.
Then expose the keywords from there with the dynamic library interface.
Working with a string representation of a js/ts is not a nice way. But working with a real importable module is much nicer.
So a remote interface to js/ts.

**Comment by aaltat** [comment]
Importing TS/JS code feels better option. No idea how to do it tough.

**Comment by mkorpela** [comment]
I think it should happen already in the library import. So yet another argument for the init.
That would allow people who are ok working with node.js side but do not have so much experience with python to use our library. That is most of the whole web development industry.

**Comment by mkorpela** [comment]
Done.
