### ISSUE TITLE
Add version binding between Playwright and Browser

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#591]
As @Snooz82 told me on Slack, there is no version binding between Playwright and Browser; during the installation, always the most recent version of Playwright gets downloaded.
   
I had no troubles caused by that fact so far. But I want to propose a version binding between playwright and browser. 

Despite the fact that imho a certain version of software should always result in the same installation fingerprint, a version binding would add more transparency about what's gonna be installed. 

Also for debugging purposes it would be very helpful to be able to build test scenarios with different Playwright versions under the hood.

**Comment by mkorpela** [comment]
On the same time when handling this, I propose we separate package.json and lock files used for deployment from development.

**Comment by xylix** [comment]
@aaltat I am pretty sure Playwright has a couple times broken things in minor relases in our end. I would suggest locking the playwright version expect for Patch.

Besides playwright possibly breaking things, Playwright minor releases also update the browsers. This can cause bugs, and I think we would like those bugs to be isolated to a specific Browser version if possible. (Since they are nightly / pre-release versions of the browsers even big breakage is sometimes possible.)

**Comment by aaltat** [comment]
That is also true. Also it would be better user experience if one Browser release would match to one Playwright release.

**Comment by fdaguin** [comment]
As stated by @aaltat, could the Playwright version be locked please?

**Comment by aaltat** [comment]
I did remember incorrectly and currently it is not possible to pin version easily. Hard way is to modify package.json file before running `rfbrowser init` command. I am thinking that perhaps we should allow users to decide which PW version they should install.
