### ISSUE TITLE
Delete recorded videos of successful test suites

### ISSUE THREAD

**Issue by ArminShinobi** [MarketSquare/robotframework-browser#712]
It should be possible to record all test suites at first and then only keep the videos where tests failed.
At the moment there is no correlation between the video name and failed test suites, users need to keep all videos.
This can take up a lot of space.

**Comment by aaltat** [comment]
Yes, this true and I see how that can be a problem. This is also good idea, but currently I do not have good ideas how the problem could be solved. It is pretty complex problem to solve, because context and pages might live long (depends on the library settings) and determining which page belong to which test is difficult.

**Comment by aaltat** [comment]
If we ever decide to do this, trace files should work in same way.

**Comment by aaltat** [comment]
I don't have any good ideas how to implement this, because keeping track what video belongs to which test is complicated problem to solve in a general way. In release 11 we do return the video path, which may help you to solve the problem. 

But because I don't see solution to your problem in Browser library side, I will close this issue.
