### ISSUE TITLE
Element is visible, enabled and editable, but click fails

### ISSUE THREAD

**Issue by jin-harmoney** [MarketSquare/robotframework-browser#765]
`Click` reports that the element is not visible, while `Wait For Elements State` says it is.

The following:

```
    ${selector}    Set Variable    //*[contains(@for,'question-${x}')]
    Browser.Wait For Elements State    ${selector}    state=visible
    Browser.Wait For Elements State    ${selector}    state=enabled
    Browser.Wait For Elements State    ${selector}    state=editable
    Browser.Click  ${selector}
```

Results in:

![image](https://user-images.githubusercontent.com/73221968/109973090-449ff780-7cf8-11eb-995a-62aed2ff9bc1.png)

and:

```
TimeoutError: page.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector "//*[contains(@for,'question-2000-1')]"
  selector resolved to visible <label class="disp-f" for="question-2000-1" _ngcontent-…>…</label>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not visible - waiting...
```

**Resolved to visible** is weird in combination with **waiting for element to be visible**. How can I further debug this issue?

My current workaround is to use `force=True`.

Robot related pip dependencies:

```
robotframework==3.2.2
robotframework-requests==0.6.6
robotframework-seleniumlibrary==4.5
robotframework-databaselibrary==1.2
robotframework-jsonlibrary==0.3
robotframework-websocketclient==1.3.0
robotframework-browser==3.2.0
pymysql==0.10.1
objectpath==0.6.1
```

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Chromium
 - Version: 90.0.4421.0 (Developer Build) (64-bit)

**Comment by aaltat** [comment]
Sometimes these types of solutions is needed and it is not uncommon either, but definitely not desired solution. Basically click fails, because one of the Playwright [auto waiting](https://playwright.dev/docs/actionability/) checks fails. And because determination is done by playwright we do not have control over it. 

I can see basically this happens because the playwright automatic waiting does not work in your case and app is still loading or doing something. In that case element state might change and this could happen. Like some animation running in somewhere, element needs to hoovered before click is possible or something totally different. 

But in any case there is not much we can do to fix the Browser library side, at least with this information. Therefore I am closing this issue. If you feel that there is big in the Browser library, please send a comment and we will respond.

**Comment by jin-harmoney** [comment]
@aaltat thank you for the feedback. I have the issue all over the place and my colleagues don't, so I guess this is indeed Playwright related. Maybe due to the difference in OS or browser version. I'll see if I can open an issue on their side.

I saw the following note in the robot logs: 

> Note: use DEBUG=pw:api environment variable to capture Playwright logs.

But doing `export DEBUG=pw:api` only results in an empty `playwright-log.txt` being created. Any advice on how I can further debug this?

**Comment by aaltat** [comment]
Set `enable_playwright_debug` as true when [importing](https://marketsquare.github.io/robotframework-browser/Browser.html#Importing) library.
