### ISSUE TITLE
Support for electron apps

### ISSUE THREAD

**Issue by zastress** [MarketSquare/robotframework-browser#867]
Currently, Browser library does not support running electron apps like Selenium. The way I understand it, there is some work done on Playwright side to implement Electron but not yet on Browser side.
Could this be a point of interest for the future?

**Comment by aaltat** [comment]
The electron app support is difficult because it doesn't use the browser/ contex / page model. Instead it's single application or an object, therefore it is difficult to incorporate to our library. I am not saying that it could not be done, but I am pretty sure that it could mess up the current architecture. Therefore I am closing this issue.

**Comment by Exegetech** [comment]
I see that Playwright has an experimental Electron support here https://playwright.dev/docs/api/class-electron

Is it possible to use the "extending with JS module" feature https://marketsquare.github.io/robotframework-browser/Browser.html#Extending%20Browser%20library%20with%20a%20JavaScript%20module

To have somewhat an Electron support? I am not asking this library to do it, but probably just some useful pointers.
